// vim: set expandtab ts=2 sw=2 nowrap ft=java ff=unix :
package jp.co.wktk.apiserver;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import com.mysema.query.sql.*;
import jp.co.wktk.apiserver.persistence.*; // generated by Querydsl

import org.json.simple.JSONValue;

@Path("/select")
public class ApiHandler {
  private static String url = "jdbc:mysql://localhost:3306/apiserver?useUnicode=true&characterEncoding=UTF-8";

  public ApiHandler() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
    } catch (Exception e) {
      System.exit(1);
    }
  }

  @GET
  @Produces("application/json; charset=utf-8")
  public String getMessage() {
    StringBuilder ret = new StringBuilder();
    try {
      Connection connection = DriverManager.getConnection(url, "root", "");
      QUsers users = new QUsers("users");
      SQLTemplates dialect = new MySQLTemplates();
      SQLQuery query = new SQLQueryImpl(connection, dialect);
      List<String> names = query.from(users).list(users.name);
      ret.append(JSONValue.toJSONString(names));
    } catch (SQLException e) {
      ret.append(e.toString());
    }
    return ret.toString();
  }
}
